### ISSUE TITLE
why GET operation is so fast

### ISSUE THREAD

**Issue by mosTavassoli** [orbitdb/orbitdb#1043]
Hello Everyone,
I hope that I ask my question in the correct place.

I have a simple question about the get, put, and delete operations in the key/value data model.
I am experimenting with the effect of the number of keys with a specific key size in the put/get and delete operations. I calculated the time of each operation to realize the impact of key numbers. In my test, I created an array of key numbers, [1,10,100] with the size of 100K to generate the result. 

The result shows that the GET operation did very fast in comparison to PUT and DELETE operations. There is a huge difference between put and delete operations with get.  
I put the code that I have written in this link [OrbitDB](https://github.com/mosTavassoli/OrbitDB/tree/master/new-design).
I would be grateful if you could let me know your idea about it and the result that I have got. 
Thank you so much.

**Comment by tabcat** [comment]
The reason the get method is so fast is because it is not an operation. The get method is synchronously retrieving a value that is already kept in memory. The put and delete methods create put and delete operations which must be appended to the operation log. Appends to the operation log involve creating + digitally signing + hashing a new object, and writing data to disk.

**Comment by mosTavassoli** [comment]
Thank you for your reply,
Based on your explanation, this comparison does not make sense. So, I have to experiment based on PUT and DELETE operations.

**Comment by haydenyoung** [comment]
@mosTavassoli if you could expand on what doesn't make sense from @tabcat 's explanation. For now I'll close this issue but feel free to re-open if you would like to discuss further.
