### ISSUE TITLE
Byzantine-Fault Tolerant CRDT?

### ISSUE THREAD

**Issue by stanbar** [orbitdb/orbitdb#1073]
Hi,
I'm building a p2p voting system and found [Weshnet](https://github.com/berty/weshnet) to ideally match my network assumptions. Since Weshnet uses OrbitDB, I'm asking here for help.

OrbitDB uses CRDT to achieve strong eventual consistency, however, to my best knowledge, it won't work with byzantine nodes.

In our voting protocol, we have to assume that some nodes are malicious and want to manipulate the voting results, e.g., send conflicting messages[^conflicting] to different nodes (kind of double-spending). We need some mechanism to settle conflicts between multiple valid messages received by different nodes.

[^conflicting]: For example, a voter can prepare two valid, yet conflicting messages, first "I vote for A", and "I vote for B", and broadcast the first message to half of the network and second message to the other half. Both messages are correct.

As [pointed out on hacker news](https://news.ycombinator.com/item?id=30561218), CRDT can not solve such conflicts, and a consensus mechanism is required. 

Something like PBFT/Tendermint/Stellar Consensus Protocol (FBA) would work best. Can you suggest me some approach? Or maybe someone else tried to do that?

**Comment by Erudition** [comment]
Suggestion, another IPFS project called the ODD SDK does use Byzantine Fault Tolerant CRDTs, and natively supports encryption, and may be suitable for your use case since it doesn't require lots of rapid updates (currently ODD just use the Webnative File System, so you save things to IPFS as if they were files and folders).

I love weshnet btw, can't wait for it to mature. The real innovation is the go-mobile-ipfs implementation though, allowing native bluetooth stack connections for IPFS, so ODD would be able to take advantage of that too!

**Comment by haadcode** [comment]
I believe BFT CRDTs alone, in the context of eventual consistency, won't solve the problem as described here and indeed you'd need a consensus system ((global state) to prevent those "double-spends".
