### ISSUE TITLE
benchmarks?

### ISSUE THREAD

**Issue by whyrusleeping** [orbitdb/orbitdb#238]
Hey @haadcode, It would be great to have a set of benchmarks for orbitdb that would allow us over in ipfs-land to ensure that we're always pushing changes that improve performance for projects that use ipfs. 

Thanks :)

**Comment by haadcode** [comment]
@whyrusleeping you hit my favorite topic :) been benchmarking since day 1.

Would these get you started?  https://github.com/orbitdb/orbit-db/blob/master/examples/benchmark.js and https://github.com/haadcode/ipfs-log/tree/master/benchmarks (should work with go-ipfs through js-ipfs-api)

We don't have benchmarks for network throughput atm, which would be great to have.

Anything else you have in mind to benchmark?

**Comment by haadcode** [comment]
You might find the [benchmarks for ipfs-log](https://github.com/orbitdb/ipfs-log/tree/master/benchmarks) helpful to benchmark some parts of IPFS (it only uses object.get/.put). 

More updated benchmarks coming in soon for OrbitDB.

**Comment by haadcode** [comment]
We now have more [benchmarks](https://github.com/orbitdb/orbit-db/tree/master/benchmarks) for OrbitDB.

**Comment by haydenyoung** [comment]
Latest orbitdb including a number of benchmarks. We can continue to expand on them as required.
