### ISSUE TITLE
ActivityPub integration for OrbitDB

### ISSUE THREAD

**Issue by MirceaKitsune** [orbitdb/orbitdb#478]
One of my ambitions has been to see a decentralized and serverless social media platform, up to the same quality standards as Twitter and Facebook. Using IPFS and OrbitDB this dream is now much closer to becoming a reality. I wanted to bring up one important subject in this regard: The ActivityPub protocol, and how OrbitDB can interact with it.

https://en.wikipedia.org/wiki/ActivityPub

I have been following the Mastodon social media platform. It is decentralized but not so much serverless: You need to jump through quite a few loops to setup an instance on your computer, while a central server still maintains the database and handles much of the processing. I've briefly asked the team to what extent it could be made serverless and was introduced to AP. ActivityPub is a standardized API for social media: It's a way to create, modify and delete content across different platforms. It makes it easier for multiple products to communicate with one another and share certain data, which will be a huge bonus as more decentralized platforms emerge.

My question is: To what extent can OrbitDB integrate ActivityPub support? Would it be possible to create a module that allows browsers to translate ActivityPub requests into entries stored into an Orbit database? It does feel like docstore would be the best candidate for such a thing: It can create, modify, remove and index entries which should be exactly what the API expects. The data is stored as a JS object, and thanks to indexing every request should be easy and efficient to address.

If such a tool could be developed, fully decentralized social media might be a great step closer to becoming possible. Right now you still need to run a server, but with such an approach you could have an entire Twitter alternative running entirely in the web browsers of users! IPFS can already handle media storage, but storing the dynamic user data without using a server remains a problem... this may very well fix that final limitation. What are your thoughts on this?

**Comment by gyuri-lajos** [comment]
Back in the day I had the same ambition but not with ActivityPub, because it is the Fediverse communities of people are the hub.
I was interested in Gossip networks but without a Pub.
2 years on we are ready to start building the IndiVerse of HyperMedia where each participant can weave their own overlapping social networks of trust and act as their own(ed) WebNative Hub in the network powered by IPFS https://fission.codes/ and OrbitDb. Hope to see the IndieHub kernel in the list of Awesome OrbitDb

**Comment by haydenyoung** [comment]
I wonder if this is a better discussion to be had with the Libp2p team as ActivityPub seems like a better fit at the pubsub prootocol level.

I'll close this for now but feel free to re-open if this is a discussion to be had directly with OrbitDB. Otherwise I would recommend including the Libp2p guys in on this discussion.
