### ISSUE TITLE
Mem leak

### ISSUE THREAD

**Issue by phillmac** [orbitdb/orbitdb#581]
Over several hours the ram consumed by the JS VM increases massively.
database writer function:
```
async function init() {
    try {
        db = await orbitdb.open(dbaddr, {type:'docstore', create:true, replicate:true})
        await db.load()
        console.log(db.id)
        console.log('db loaded')
        setInterval(write_db, 60*1000)
    } catch (e) {
        console.error(e)
        process.exit(1)
    }
}
async function write_db () {
    test = db.get('test')
    if ( test.length == 0) test.push({'data':[]})
    data = test[0]['data'] || []
    nd = Math.random().toString(36).substring(7)
    data.push(nd)
    console.log('Adding ' + nd)
    await db.put({_id:'test', 'data': data})
}
```
browser code: [Gist](https://gist.github.com/phillmac/9bc80d06e523fe7bd8c944d342029f53)
![](https://files.gitter.im/orbitdb/Lobby/VQIK/image.png)

orbit-db version: 0.19.9
Browser: chrome

**Comment by haadcode** [comment]
This should be fixed in 1.0.0. Note the [new package name](https://www.npmjs.com/package/@orbitdb/core). There used be bunch of issues regarding mem leaks in the past due to webrtc and also due to orbitdb which now should be addressed in v1.0.0.

If the issue persists, feel free to re-open the issue.
