### ISSUE TITLE
How to make my database accessible online

### ISSUE THREAD

**Issue by devanshusehgal** [orbitdb/orbitdb#789]
I'm running my IPFS daemon as instructed here [Module with IPFS Daemon](https://github.com/orbitdb/orbit-db#module-with-ipfs-daemon) and I created a new Database in my nodejs code -

```
const IpfsClient = require('ipfs-http-client')
const OrbitDB = require('orbit-db')

const ipfs = IpfsClient('/ip4/127.0.0.1/tcp/5001')

OrbitDB.createInstance(ipfs).then(orbitdb => {
	orbitdb.log('hello').then(db => {
		console.log(db.address.toString());
	})
})
```

Daemon -
![daemon](https://user-images.githubusercontent.com/38864946/81498263-88e18780-92e1-11ea-8fe6-42c3c0ead953.png)

Node App -
![create](https://user-images.githubusercontent.com/38864946/81498281-9a2a9400-92e1-11ea-96fc-4528a98de08e.png)

When I try to access my Database from the `Open Remote Database` option in [Demo 1 Page](https://ipfs.io/ipfs/QmeESXh9wPib8Xz7hdRzHuYLDuEUgkYTSuujZ2phQfvznQ/) it never connects to the Database.

![remote](https://user-images.githubusercontent.com/38864946/81498318-d827b800-92e1-11ea-9a39-991a379917d5.png)
![console](https://user-images.githubusercontent.com/38864946/81498319-dbbb3f00-92e1-11ea-960b-c9da11b28aea.png)

How do I put my database online? Please help. Thanks :)

**Comment by devanshusehgal** [comment]
After creating the database no new files were pinned either. I was under the impression that the database would be stored in some file and be pinned like other IPFS files.

**Comment by phillmac** [comment]
Pinning is turned off be default because its a massive performance hit, hiwever it is possible to turn it on via the options

**Comment by devanshusehgal** [comment]
Thanks, can you please tell how to enable it? Also would pinning the data mean that it's accessible to other nodes (and they can process it) even when my node is offline?

**Comment by phillmac** [comment]
Pinning usually doesn't affect whether the data is accessible, unless the ipfs node is performing garbage collection because it's repo has exceeded the max size.
To enable pinning, set the options param to contain ` { pin: true }` as mentioned in the docs here https://github.com/orbitdb/orbit-db/blob/f2cfaa8d1a10bc1f4d589442308f88bb5e976cb2/GUIDE.md#add-an-entry

Also, perhaps try this version of the demo, https://ipfs.io/ipfs/Qma4jzYSZkzUt4Tz4Pxr7KGupHCViaFNZh13bsEhovPkZp
It's the same as the demo you linked, except the `ipfs` version is slightly newer, and has the `relay` option enabled by default. What this mean is you can easily connect your ipfs nodes together with the `p2p-circuit` address that is listed in the browser. e.g. 
![image](https://user-images.githubusercontent.com/4534835/81542773-87cf5980-93b8-11ea-8d4a-39c696906669.png)

Tell the ipfs daemon instance to connect to the browser instance:
`ipfs swarm connect /p2p-circuit/ipfs/QmNS8nB6w6XVkvSpEFPHF19nJoHju4Lxi1pktMZmfJ8Zn`

**Comment by aphelionz** [comment]
Note the websocket-star mutliaddr in this screenshot:

![image](https://user-images.githubusercontent.com/106148/81575992-b11ac600-9375-11ea-9884-fe2615abcf8e.png)

That will be the key to swarming between the a browser and a node.js node, it's called a "signaling" server: https://ws-star.discovery.libp2p.io/

**Comment by devanshusehgal** [comment]
This [OrbitDB Guide Chapter](https://github.com/orbitdb/field-manual/blob/master/01_Tutorial/04_P2P_Part_1.md) clarified everything for me. 

But I'm not getting any swarms when I'm running my app in browser. I do get peers though.
![WhatsApp Image 2020-05-12 at 01 08 38](https://user-images.githubusercontent.com/38864946/81604191-237abd00-93ed-11ea-9988-3c1ad33fb8b3.jpeg)

And when I try to pass an address in `Swarm` in IPFS config I get these errors and after that the app never works until I delete all IndexedDB data in the browser.
![WhatsApp Image 2020-05-12 at 01 03 40](https://user-images.githubusercontent.com/38864946/81603841-a0596700-93ec-11ea-80b8-fba7f2c49ffd.jpeg)

This is the config with Swarm address passed -
```
// Init IPFS and OrbitDB
const node = await Ipfs.create({
	relay: { enabled: true },
	hop: { enabled: true, active: true },
	EXPERIMENTAL: { pubsub: true },
	config: {
		Addresses: {
			Swarm: [
				'/dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star',
			]
		}
	}
});
const orbitdb = await OrbitDB.createInstance(node);
console.log(`IPFS Node Id - ${orbitdb.id}`);
console.log(`OrbitDB Id - ${orbitdb.identity.id}`);
```

**Comment by haydenyoung** [comment]
Is this still a problem? You may need to explicitly dial the other peer using `ipfs.swarm.connect`. Closing for now but please re-open if problems persist.
