### ISSUE TITLE
How about performance?

### ISSUE THREAD

**Issue by GildedHonour** [orbitdb/orbitdb#850]
In a nutshell, can OrbitDb be used as a Real Time database? Where read and write operations will take 1, or several seconds at most.

**Comment by RichardLitt** [comment]
OrbitDB is limited by the underlying restrictions of IPFS, to me knowledge. So, if it works on IPFS, it'll work on OrbitDB. Hope this helps.

**Comment by JaniAnttonen** [comment]
^ Which means that it is local/offline first. Local changes sync "real-time" and global changes sync as they sync. Since it's based on a CRDT, there's no single source of truth, but rather eventual consistency. Most of all it's related to things like if the peer you want to share your data with has a direct connection with you or not, and how fast that connection is.

**Comment by haadcode** [comment]
> can OrbitDb be used as a Real Time database? Where read and write operations will take 1, or several seconds at most.

yes, it is a real time database.

**Comment by haydenyoung** [comment]
Issue appears to be answered. Closing, but feel free to re-open if any more questions arise.
