### ISSUE TITLE
Automate orbitdb releases

### ISSUE THREAD

**Issue by holmesworcester** [orbitdb/orbitdb#899]
From https://github.com/orbitdb/orbit-db/issues/819#developer-experience-the-publish-dance:

```
Developer Experience: The Publish Dance

One of the biggest hurdles to releases is a term the contributors call the "publish dance" which requires a coordinated effort of publishing around 20 different npm modules that together constitute an OrbitDB release. There's no need to enumerate them here but the process generally starts from ipfs-log and moves upward to the top-level orbit-db.

The community has discussed about solving this on tooling level, such as using Lerna for module management, but a better alternative would be to address this on the architecture / implementation level by:

* remove the inheritance of stores and inject the Store module to stores
* remove ipfs-log dependency from Store and inject it from OrbitDB
* generally switch all inheritance to dependency injection (eg. feedstore takes in as a parameter an eventstore instead of inheriting from it)

All these would make it possible to configure the dependencies on the main package level, in orbit-db, giving the users more flexibility in choosing which modules and versions they use.
```

Success criteria: OrbitDB can deploy a new release to npm.

Context: OrbitDB already uses Circle CI, but if that's inconvenient for some reason, Github Actions would work too.

**Comment by aphelionz** [comment]
The current manual process is essentially: start at the bottom of this chart and upgrade everything and their dependents on the way up.

![image](https://user-images.githubusercontent.com/106148/127239875-1dba2385-229a-4876-a91a-20a6626f618d.png)

Each of those get published to their own npm package, and then everything is collated in `orbitdb/orbit-db` for the final and "official" release.

We already have CI (via high test coverage and the battery of tests on every PR). I've already done some streamlining by using `peerDependencies` for the packages higher in the chart. However, we have no continuous deployment and that's really what we need if the project is going to be as active and resilient as it needs to be.

I think at bare minimum we need:
1. Cross package tests, i.e. I update `orbit-db-store` and it runs tests in `orbit-db` with that package activated
2. Automated publication to the `next` tag on NPM for every commit to master
3. A one-click manual workflow to make the current `next` tag on NPM the current one.

Open to questions / comments / suggestions

**Comment by aphelionz** [comment]
As an example, I just wired up https://github.com/orbitdb/orbit-db-test-utils with some of the above. It publishes to npm on every git tag, as well as to the `next` tag on every push to `main`

**Comment by aphelionz** [comment]
Checklist:

[x] - https://github.com/orbitdb/orbit-db-test-utils
[ ] - https://github.com/orbitdb/orbit-db-io
[ ] - https://github.com/orbitdb/ipfs-log
[ ] - https://github.com/orbitdb/orbit-db-store
[ ] - https://github.com/orbitdb/orbit-db-counterstore
[ ] - https://github.com/orbitdb/orbit-db-feedstore
[ ] - https://github.com/orbitdb/orbit-db-kvstore
[ ] - https://github.com/orbitdb/orbit-db-eventstore
[ ] - https://github.com/orbitdb/orbit-db-docstore
[ ] - https://github.com/orbitdb/orbit-db-storage-adapter
[ ] - https://github.com/orbitdb/orbit-db-keystore
[ ] - https://github.com/orbitdb/orbit-db-cache
[ ] - https://github.com/orbitdb/orbit-db-identity-provider
[ ] - https://github.com/orbitdb/orbit-db-pubsub




Other / deprecated / otherwise left out:
- https://github.com/orbitdb/crdts
- https://github.com/orbitdb/orbit-db-cli
- https://github.com/orbitdb/orbit-db-benchmark-runner
- https://github.com/orbitdb/welcome
- https://github.com/orbitdb/research
- https://github.com/orbitdb/logo
- https://github.com/orbitdb/awesome-orbitdb

**Comment by julienmalard** [comment]
@aphelionz Please let me know if community contributions (pull requests) for the above would be useful!

**Comment by aphelionz** [comment]
@julienmalard yes please! You can use https://github.com/orbitdb/orbit-db-test-utils and https://github.com/orbitdb/orbit-db-io as exemplars

**Comment by aphelionz** [comment]
`orbit-db-store` taken care of by @julienmalard

**Comment by julienmalard** [comment]
Hello,

I took a try at injecting dependencies as suggested. Here's a preliminary first try: https://github.com/julienmalard/orbit-db-feedstore

Is this what you had in mind? This injection approach would however require some reworking of how these modules are used (i.e., removing most orbit-related dependencies in package.json for all but the top-level orbit-db, and also replacing class instantiations with calling a function that will generate this class).

Please let me know what you think!

**Comment by haydenyoung** [comment]
Much of this has now been addressed in the @orbitdb/core super package along with some updates to the release cycle. Am closing for now but feel free to re-open if this issue still requires resolution.
