### ISSUE TITLE
Oplog Watermarks

### ISSUE THREAD

**Issue by CSDUMMI** [orbitdb/orbitdb#922]
I want to move the discussion of [this project](https://github.com/orgs/orbitdb/projects/7#card-44572255) out of the [Road to 1.0](https://github.com/orbitdb/orbit-db/issues/819) .

## Oplog Watermarks

As of right now, the kvstore and docstore currently reduce the full log any time updateIndex is called, which is on every write to the oplog. This is slow, grows even slower over time and ultimately unnecessary.

A solution to this could be to add high/low watermark and only process "new oplog entries". This is highly applicable especially for KVStore and DocStore.

**Comment by Jon-Biz** [comment]
Would we want to account for out of order entries? If a oplog item was received from a peer out of order?

**Comment by CSDUMMI** [comment]
We should not be doing this in the Indexes, although we could try to implement it this by way of a change to the Index API.

Maybe moving from a single  `updateIndex` function taking and applying 
the entire `oplog` to an `applyEntry` and `clear` method, handling only
one oplog entry and allowing for the reversion of the current index
state to a specified point.

**Comment by Jon-Biz** [comment]
Right, I see that now. 

If we can retrieve all relevant changes, would we need a to revert to the previous state? Since all operations would be being reapplied in chronological order, discrepancies would be overwritten. I'm trying to think of a situation where this would not be the case.

I'm currently thinking the process might look like this:

* When new items are added to the log, we pass them to `updateIndex` first
* `updateIndex` iterates through the new items, making sure that none have an earlier clock value than the last item in the oplog
* if we finds out of order items, it should grab those items too filtering by `payload.key` so that we only pass down operations relevant to the new item. *[(Can we expect every payload to have a key?)]*
* we are done with the oplog, so we can now add the new items to it
* the store indexes receive and process the new and retrieved operations, instead of the entire oplog.

**Comment by CSDUMMI** [comment]
> if we finds out of order items, it should grab those items too, filtering by payload.key so that we only pass down operations relevant to the new item. [(Can we expect every payload to have a key?)]
No.

**Comment by CSDUMMI** [comment]
My idea was this:
1. `applyEntry(operation)` takes an operation and applies it to the current state.
2. `clear(watermark)` returns the state of the Index to the specified watermark.
3. `state()` returns the current state of the Index.

OrbitDB could then use these three functions to implement watermarks:
1. When the db is first created, the `clear()` is called without any argument => Creating an empty state.
2. Upon receiving a oplog, OrbitDB sorts them and passes them in order to `applyEntry`.
3. Every X operations OrbitDB calls `state()`  and creates a watermark from the state. 
4. When new operations are received, clear is called to restore the state to the latest watermark before the new operation and `applyEntry` is called on the new oplog from this watermark onward.

For example, if we have an oplog consisting of  five operations: [A, B, C, D, E],
OrbitDB first initializes the Index to an empty index, then calls `applyEntry` successively on A, B, C, D and E. 

Let's now assume for the sake of example, that after B was applied and after D was applied a watermark was created.

Now if OrbitDB receives an operation W which should be inserted between C and D, 
OrbitDB reverts the state of the index to the watermark made after B is applied,
applies C, W and E to the index and creates new oplogs.

I'm sorry if my example and explaination is a little convoluted I've not yet found a way to put this in a more percise form.

**Comment by haydenyoung** [comment]
[KeyValueIndexed](https://github.com/orbitdb/orbitdb/blob/main/src/databases/keyvalue-indexed.js) should now address the processing of [new entries only](https://github.com/orbitdb/orbitdb/blob/aa078efe9a2fcb0376da7ce2172ad0bad17d97a6/src/databases/keyvalue-indexed.js#L42) in the index update.
