### ISSUE TITLE
[Question] How to actually connect instances over the internet?

### ISSUE THREAD

**Issue by MinmoTech** [orbitdb/orbitdb#968]
I'm using the files from the `examples/browser` directory, but I updated the used versions of ipfs and orbitdb: 

```
    <script src="https://unpkg.com/ipfs@0.62.1/index.min.js"></script>
    <script src="https://unpkg.com/orbit-db@0.28.3/dist/orbitdb.min.js"></script>
```

You can see the files I'm using here:
https://ipfs.io/ipfs/QmSKQ32ovEAtuiZsQ4sGMQW2SB24weG8TKpR9snSDUNGWb/browser/

And directly test it here:
https://ipfs.io/ipfs/QmSKQ32ovEAtuiZsQ4sGMQW2SB24weG8TKpR9snSDUNGWb/browser/browser.html

I cannot make a connection between 2 nodes not in the same network.
I tried this with one node on my PC and the other one over the TOR network, but I also tried the mobile network with my phone.
These instances are seemingly unable to connect to each other, the instance that opens the database gets a timout:

```
TimeoutError: request timed out
    at u (index.min.js:82:112231)
    at index.min.js:82:112589
    at async Object.read (orbitdb.min.js:58953:17)
    at async OrbitDB.open (orbitdb.min.js:90234:22)
    at async HTMLButtonElement.openDatabase (example.js:208:12)
```

I also sometimes get this error in the console on either node:

```
WebSocket connection to 'wss://node3.preload.ipfs.io/p2p/QmY7JB6MQXhxHvq7dBDh4HpbH29v4yE9JRadAVpndvzySN' failed: 
```

Is there something I'm missing?
I would have assumed that the default configuration would enable me to connect over the internet, but it seems not.
Could this be solved by having a dedicated node (i.e. a proper ipfs node) for connections in the swarm peers or the bootstrap list? :)

Thank you for any help :pray:

**Comment by tabcat** [comment]
Connection errors logged to console in the browser are pretty common with ipfs/libp2p and most of the time arent the root issue. 

Not being able to fetch the manifest is the issue and requires some troubleshooting and likely adding to the ipfs/libp2p config. Since the manifest cannot be fetched, its safe to assume those nodes can't talk to each other. You can also test reach-ability with the [ipfs.ping](https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/MISCELLANEOUS.md#ipfspingpeerid-options) tool.

For troubleshooting orbitdb replication the ipfs.dag.get, ipfs.ping, and ipfs.pubsub apis will be the most helpful. And reading ipfs/libp2p docs about connecting nodes will assist in setting up an environment where those troubleshooting commands can succeed.

**Comment by juligreen** [comment]
Thank you so much for this answer, I will report back with any findings!

**Comment by juligreen** [comment]
It seems my problems are actually only happening when running behind TOR.
Does anyone have tips for creating connections in that case or is it maybe unsupported?

**Comment by tabcat** [comment]
The only person I remember hearing trying this would be @holmesworcester

**Comment by MinmoTech** [comment]
@holmesworcester No problem, thanks for the reply!

Could you maybe quickly explain how this works on a conceptual level?
Since it's not becoming quite clear to me just from the code.
Also, do you think the solution could be upstreamed to libp2p?

> we used a closed network though, so our setup might be a bit different.

What does a closed network mean in this case? :)

**Comment by holmesworcester** [comment]
Re upstreaming to libp2p, Tor is still a bit of a 'sidecar' so I'm not sure how packaging etc would work. Do you think libp2p maintainers would accept a module that requires a Tor binary for each platform?

Conceptually, we use the libp2p websocket transport with Tor onion addresses in the place of web addresses. So everyone has a persistent address.

Whoever starts a network (we call networks communities because we're building a Slack like chat app, but really it applies to any situation where some people want to share some state) launches a special onion address we call a registrar. The registrar accepts requests to enter a community, adds peer info to an orbitdb table, and gives the new user an onion address they can begin syncing from. 

At this point, every online user who has joined the community can connect to each other and share state using IPFS and orbitdb. 

There's a bit more detail about how we discover the orbitdb's and how we use certificates/pki to restrict access to the community but the above is how the networking piece works. 

One downside is that the community creator currently has to be online for new users to join, but we can relax this requirement by adding some complexity in the future. 

The main ideas here are: Tor and libp2p websockets work nicely together, Tor addresses are persistent so peer discovery isn't an issue once you learn one peer address, Tor makes NAT traversal not an issue, and Tor addresses (v3 onion addresses) aren't guessable so there's some built in security there.

**Comment by holmesworcester** [comment]
Also, in the future the Tor project's work on Arti (Tor in Rust and also potentially WASM) make all the Tor stuff much easier to package up, and it might even work well in browsers someday, using either webrtc or websockets to connect to Snowflake nodes.

**Comment by MinmoTech** [comment]
Oh wow, it's incredibly cool what you're doing!
I didn't know you were even able to use TOR peer-routing this way!

Though it's not exactly my use-case, I was just looking to be able to have connections in js-ipfs running in a browser but behind tor (I was simply using the built-in tor window of the brave-browser) since it's intended for end-users without technical knowledge, I just want people to have the possibility of being behind TOR for anonymity.

On the topic of upstreaming to libp2p, with the tor binary dependency I'm not sure how well it would work, but as soon as it will use Arti compiled to WASM I'm very sure they'd be interested!

Thanks again for your help and the super interesting write-up!

**Comment by haydenyoung** [comment]
Recommend asking libp2p re: connection issues. Our aim at OrbitDB is to facilitate easier p2p connections but this will be something we need to closely with libp2p on. Closing for now.
