### ISSUE TITLE
Is OrbitDB a good option for a collaborative, crowd-sourced distributed metadata database for a file organizer with auto-tagging?

### ISSUE THREAD

**Issue by ghost** [orbitdb/orbitdb#996]
I would like to do [a collaborative, crowd-sourced distributed database for a file organizer with auto-tagging](https://gist.github.com/HarleyQuinn-Z6/0bfe0d616679cb634fe1f170de38a226) where each user has a copy and changes are voted between the users and applied to all databases when they are approved. Is OrbitDB a good option for this or is there anything simpler?

**Comment by Erudition** [comment]
Peerbit may be a better choice for that scale of collaboration.
However, the idea of "the application and not the user" doesn't really work in a p2p database since they are one in the same, no way to prevent a user from acting on behalf of "the application". So it sounds like you need a server for running "the application" part, or a smart contract.
Alternatively, you can look into Holochain which is more than a p2p database and allows thing such as not permitting writes unless they're signed with validity based on custom rules (such as "had enough votes") that are enforced by every peer.

**Comment by haydenyoung** [comment]
I would recommend [reaching out to the community](https://matrix.to/#/#orbitdb_Lobby:gitter.im) to discuss your requirements in more detail.
